services:
  noether:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        DISTRO: humble
    environment:
      ROS_LOG_DIR: /tmp
      ROS_LOCALHOST_ONLY: $ROS_LOCALHOST_ONLY
      ROS_DOMAIN_ID: $ROS_DOMAIN_ID
    container_name: noether_ros
    image: ghcr.io/ros-industrial/noether_ros:humble
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    privileged: false
